/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as AppIndexImport } from './routes/app/index'
import { Route as MarketingLayoutImport } from './routes/_marketing/_layout'
import { Route as MarketingLayoutIndexImport } from './routes/_marketing/_layout/index'
import { Route as MarketingLayoutResumeTemplatesImport } from './routes/_marketing/_layout/resume-templates'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const AppIndexRoute = AppIndexImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRoute,
} as any)

const MarketingLayoutRoute = MarketingLayoutImport.update({
  id: '/_marketing/_layout',
  getParentRoute: () => rootRoute,
} as any)

const MarketingLayoutIndexRoute = MarketingLayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingLayoutRoute,
} as any)

const MarketingLayoutResumeTemplatesRoute =
  MarketingLayoutResumeTemplatesImport.update({
    id: '/resume-templates',
    path: '/resume-templates',
    getParentRoute: () => MarketingLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/_marketing/_layout': {
      id: '/_marketing/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MarketingLayoutImport
      parentRoute: typeof rootRoute
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppIndexImport
      parentRoute: typeof rootRoute
    }
    '/_marketing/_layout/resume-templates': {
      id: '/_marketing/_layout/resume-templates'
      path: '/resume-templates'
      fullPath: '/resume-templates'
      preLoaderRoute: typeof MarketingLayoutResumeTemplatesImport
      parentRoute: typeof MarketingLayoutImport
    }
    '/_marketing/_layout/': {
      id: '/_marketing/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingLayoutIndexImport
      parentRoute: typeof MarketingLayoutImport
    }
  }
}

// Create and export the route tree

interface MarketingLayoutRouteChildren {
  MarketingLayoutResumeTemplatesRoute: typeof MarketingLayoutResumeTemplatesRoute
  MarketingLayoutIndexRoute: typeof MarketingLayoutIndexRoute
}

const MarketingLayoutRouteChildren: MarketingLayoutRouteChildren = {
  MarketingLayoutResumeTemplatesRoute: MarketingLayoutResumeTemplatesRoute,
  MarketingLayoutIndexRoute: MarketingLayoutIndexRoute,
}

const MarketingLayoutRouteWithChildren = MarketingLayoutRoute._addFileChildren(
  MarketingLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '/about': typeof AboutRoute
  '': typeof MarketingLayoutRouteWithChildren
  '/app': typeof AppIndexRoute
  '/resume-templates': typeof MarketingLayoutResumeTemplatesRoute
  '/': typeof MarketingLayoutIndexRoute
}

export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/app': typeof AppIndexRoute
  '/resume-templates': typeof MarketingLayoutResumeTemplatesRoute
  '/': typeof MarketingLayoutIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/about': typeof AboutRoute
  '/_marketing/_layout': typeof MarketingLayoutRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/_marketing/_layout/resume-templates': typeof MarketingLayoutResumeTemplatesRoute
  '/_marketing/_layout/': typeof MarketingLayoutIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/about' | '' | '/app' | '/resume-templates' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/app' | '/resume-templates' | '/'
  id:
    | '__root__'
    | '/about'
    | '/_marketing/_layout'
    | '/app/'
    | '/_marketing/_layout/resume-templates'
    | '/_marketing/_layout/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AboutRoute: typeof AboutRoute
  MarketingLayoutRoute: typeof MarketingLayoutRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  AboutRoute: AboutRoute,
  MarketingLayoutRoute: MarketingLayoutRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/about",
        "/_marketing/_layout",
        "/app/"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/_marketing/_layout": {
      "filePath": "_marketing/_layout.tsx",
      "children": [
        "/_marketing/_layout/resume-templates",
        "/_marketing/_layout/"
      ]
    },
    "/app/": {
      "filePath": "app/index.tsx"
    },
    "/_marketing/_layout/resume-templates": {
      "filePath": "_marketing/_layout/resume-templates.tsx",
      "parent": "/_marketing/_layout"
    },
    "/_marketing/_layout/": {
      "filePath": "_marketing/_layout/index.tsx",
      "parent": "/_marketing/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
