/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as AppRouteImport } from './routes/app/route'
import { Route as AppIndexImport } from './routes/app/index'
import { Route as AppDashboardImport } from './routes/app/dashboard'
import { Route as MarketingLayoutImport } from './routes/_marketing/_layout'
import { Route as MarketingLayoutIndexImport } from './routes/_marketing/_layout/index'
import { Route as MarketingLayoutResumeTemplatesImport } from './routes/_marketing/_layout/resume-templates'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const AppRouteRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRoute,
} as any)

const AppIndexRoute = AppIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppDashboardRoute = AppDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)

const MarketingLayoutRoute = MarketingLayoutImport.update({
  id: '/_marketing/_layout',
  getParentRoute: () => rootRoute,
} as any)

const MarketingLayoutIndexRoute = MarketingLayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingLayoutRoute,
} as any)

const MarketingLayoutResumeTemplatesRoute =
  MarketingLayoutResumeTemplatesImport.update({
    id: '/resume-templates',
    path: '/resume-templates',
    getParentRoute: () => MarketingLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/_marketing/_layout': {
      id: '/_marketing/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MarketingLayoutImport
      parentRoute: typeof rootRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardImport
      parentRoute: typeof AppRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexImport
      parentRoute: typeof AppRouteImport
    }
    '/_marketing/_layout/resume-templates': {
      id: '/_marketing/_layout/resume-templates'
      path: '/resume-templates'
      fullPath: '/resume-templates'
      preLoaderRoute: typeof MarketingLayoutResumeTemplatesImport
      parentRoute: typeof MarketingLayoutImport
    }
    '/_marketing/_layout/': {
      id: '/_marketing/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingLayoutIndexImport
      parentRoute: typeof MarketingLayoutImport
    }
  }
}

// Create and export the route tree

interface AppRouteRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface MarketingLayoutRouteChildren {
  MarketingLayoutResumeTemplatesRoute: typeof MarketingLayoutResumeTemplatesRoute
  MarketingLayoutIndexRoute: typeof MarketingLayoutIndexRoute
}

const MarketingLayoutRouteChildren: MarketingLayoutRouteChildren = {
  MarketingLayoutResumeTemplatesRoute: MarketingLayoutResumeTemplatesRoute,
  MarketingLayoutIndexRoute: MarketingLayoutIndexRoute,
}

const MarketingLayoutRouteWithChildren = MarketingLayoutRoute._addFileChildren(
  MarketingLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '/app': typeof AppRouteRouteWithChildren
  '/about': typeof AboutRoute
  '': typeof MarketingLayoutRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/': typeof AppIndexRoute
  '/resume-templates': typeof MarketingLayoutResumeTemplatesRoute
  '/': typeof MarketingLayoutIndexRoute
}

export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app': typeof AppIndexRoute
  '/resume-templates': typeof MarketingLayoutResumeTemplatesRoute
  '/': typeof MarketingLayoutIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/app': typeof AppRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/_marketing/_layout': typeof MarketingLayoutRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/': typeof AppIndexRoute
  '/_marketing/_layout/resume-templates': typeof MarketingLayoutResumeTemplatesRoute
  '/_marketing/_layout/': typeof MarketingLayoutIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/app'
    | '/about'
    | ''
    | '/app/dashboard'
    | '/app/'
    | '/resume-templates'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/app/dashboard' | '/app' | '/resume-templates' | '/'
  id:
    | '__root__'
    | '/app'
    | '/about'
    | '/_marketing/_layout'
    | '/app/dashboard'
    | '/app/'
    | '/_marketing/_layout/resume-templates'
    | '/_marketing/_layout/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  MarketingLayoutRoute: typeof MarketingLayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  MarketingLayoutRoute: MarketingLayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/app",
        "/about",
        "/_marketing/_layout"
      ]
    },
    "/app": {
      "filePath": "app/route.tsx",
      "children": [
        "/app/dashboard",
        "/app/"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/_marketing/_layout": {
      "filePath": "_marketing/_layout.tsx",
      "children": [
        "/_marketing/_layout/resume-templates",
        "/_marketing/_layout/"
      ]
    },
    "/app/dashboard": {
      "filePath": "app/dashboard.tsx",
      "parent": "/app"
    },
    "/app/": {
      "filePath": "app/index.tsx",
      "parent": "/app"
    },
    "/_marketing/_layout/resume-templates": {
      "filePath": "_marketing/_layout/resume-templates.tsx",
      "parent": "/_marketing/_layout"
    },
    "/_marketing/_layout/": {
      "filePath": "_marketing/_layout/index.tsx",
      "parent": "/_marketing/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
